# Immigrant Project

### Cross-Generational Differences in Hispanic Outcomes by Urbanicity

*Including #1 as the instructions for Gender (#2) are similar to #1*
1.	Cross-Generational Differences in Hispanic Outcomes, 1994-2016: use main_national again, and plot the values for white-All; Hispanic-All; Hispanic, 1st; Hispanic, 2nd; and Hispanic, 3rd for each outcome listed above other than gen1-gen3. 

2.	Cross-Generational Differences in Hispanic Outcomes by Urbanicity, 1994-2016: similar to (3) broken down by geographical location, side-by-side would be great other than gen1-gen3.

In [10]:
import pandas as pd
import os
import plotly.graph_objs as go
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State

In [11]:
os.chdir(r'H:\CALDER\CALDER Data Visualizations\Data\Immigrant Project')

In [12]:
urban = pd.read_csv('main_national_city_outcomes.csv')

In [13]:
urban = urban.sort_values(by=['year', 'wbhao', 'igen'])
urban.head(8)

,year,wbhao,centcity,igen,lths,scol,college,hinsured,employed,married2,children,gen1,gen2,gen3,rincp_all
6,1994,Hispanic,0,1st Generation,0.502656,0.280816,0.122696,0.586766,0.695268,0.723819,0.750334,NaN,NaN,NaN,24236.658
7,1994,Hispanic,1,1st Generation,0.508645,0.221100,0.072965,0.537336,0.660467,0.652759,0.698410,NaN,NaN,NaN,20358.793
10,1994,Hispanic,0,2nd Generation,0.209893,0.444058,0.130711,0.781649,0.723537,0.651250,0.603461,NaN,NaN,NaN,35556.793
11,1994,Hispanic,1,2nd Generation,0.335745,0.348523,0.104569,0.730320,0.615950,0.507023,0.577815,NaN,NaN,NaN,32315.545
14,1994,Hispanic,0,3rd Generation,0.178077,0.395036,0.095554,0.792928,0.792313,0.692457,0.677977,NaN,NaN,NaN,35635.969
15,1994,Hispanic,1,3rd Generation,0.203998,0.365260,0.098718,0.755048,0.762513,0.557245,0.615464,NaN,NaN,NaN,37486.031
18,1994,Hispanic,0,All,0.351645,0.346122,0.116633,0.684487,0.728447,0.700282,0.700184,0.514948,0.202010,0.283042,29083.990
19,1994,Hispanic,1,All,0.416970,0.275438,0.084796,0.619529,0.666566,0.602027,0.655787,0.595181,0.240249,0.164570,24882.971

In [14]:
# Rename Columns
pre = ['lths', 'college', 'hinsured', 'employed', 'married2', 'children', 'gen1', 'gen2', 'gen3','rincp_all']
post = ["% less than High School diploma", "% with College Degree", "% with Health Insurance", "% Employed", "% Married", 
        "% with Children", "Share of 1st Generation", "Share of 2nd Generation", "Share of 3rd Generation", 
        "Median Individual Real Income"]
for i in range(0, len(pre)):   
    urban.rename(columns={pre[i]: post[i]}, inplace=True)

urban.columns

Index(['year', 'wbhao', 'centcity', 'igen', '% less than High School diploma',
       'scol', '% with College Degree', '% with Health Insurance',
       '% Employed', '% Married', '% with Children', 'Share of 1st Generation',
       'Share of 2nd Generation', 'Share of 3rd Generation',
       'Median Individual Real Income'],
      dtype='object')

In [15]:
urban['wbhao_igen'] = urban['wbhao'] + ' ' + urban['igen']

### Drop Columns to match Umut's request in #1

In [16]:
urban = urban.drop(urban[(urban.wbhao_igen == 'White 1st Generation') | (urban.wbhao_igen == 'White 2nd Generation')
                       | (urban.wbhao_igen == 'White 3rd Generation')].index)

In [17]:
urban = urban.drop(['Share of 1st Generation','Share of 2nd Generation', 'Share of 3rd Generation'], axis=1)

In [18]:
urban.head(8)

,year,wbhao,centcity,igen,% less than High School diploma,scol,% with College Degree,% with Health Insurance,% Employed,% Married,% with Children,Median Individual Real Income,wbhao_igen
6,1994,Hispanic,0,1st Generation,0.502656,0.280816,0.122696,0.586766,0.695268,0.723819,0.750334,24236.658,Hispanic 1st Generation
7,1994,Hispanic,1,1st Generation,0.508645,0.221100,0.072965,0.537336,0.660467,0.652759,0.698410,20358.793,Hispanic 1st Generation
10,1994,Hispanic,0,2nd Generation,0.209893,0.444058,0.130711,0.781649,0.723537,0.651250,0.603461,35556.793,Hispanic 2nd Generation
11,1994,Hispanic,1,2nd Generation,0.335745,0.348523,0.104569,0.730320,0.615950,0.507023,0.577815,32315.545,Hispanic 2nd Generation
14,1994,Hispanic,0,3rd Generation,0.178077,0.395036,0.095554,0.792928,0.792313,0.692457,0.677977,35635.969,Hispanic 3rd Generation
15,1994,Hispanic,1,3rd Generation,0.203998,0.365260,0.098718,0.755048,0.762513,0.557245,0.615464,37486.031,Hispanic 3rd Generation
18,1994,Hispanic,0,All,0.351645,0.346122,0.116633,0.684487,0.728447,0.700282,0.700184,29083.990,Hispanic All
19,1994,Hispanic,1,All,0.416970,0.275438,0.084796,0.619529,0.666566,0.602027,0.655787,24882.971,Hispanic All

## Export data

Export to git repository

In [19]:
os.chdir('H:\CALDER\CALDER Data Visualizations\Git\Immigrant-Project\Graph 4')

In [20]:
urban.to_csv('clean_national_city_outcomes.csv')

## Graph

In [4]:
app = dash.Dash()

app.css.append_css({"external_url": "https://codepen.io/chriddyp/pen/bWLwgP.css"}) 

# df = urban
df = pd.read_csv('https://raw.githubusercontent.com/otteheng/Immigrant-Project/master/Graph%204/clean_national_city_outcomes.csv')

outcomes = ["% less than High School diploma", "% with College Degree", "% with Health Insurance", "% Employed", 
            "% Married", "% with Children", "Median Individual Real Income"]

# Organize where items will be on the page
app.layout = html.Div([
        html.H3(
            children='Cross-Generational Differences in Hispanic Outcomes by Urbanicity, 1994-2016',
            style={
                'textAlign': 'center', 'fontFamily' : 'Georgia'
            }
        ),
        html.Center([          
            html.Div([
                html.Div([html.P('Select Outcome',id='outcome-title')],
                    style={'textAlign': 'center', 'fontFamily': 'Georgia'}),
                dcc.Dropdown(
                    id='outcome-id',
                    options=[{'label': i, 'value': i} for i in outcomes],
                    value='% less than High School diploma')
                ],style={'width': '50%','textAlign': 'center', 'fontFamily': 'Georgia', 'display': 'inline-block'}),        
            ]),
            html.Div([
                html.Div([
                    dcc.Graph(id='indicator-graphic1',
                              config={'modeBarButtonsToRemove': ['sendDataToCloud', 'lasso2d', 'zoomIn2d', 'zoomOut2d', 'pan2d', 
                                                                 'zoom2d','resetScale2d'], 
                                    'displaylogo': False})
                    ], style={'width': '50%', 'display': 'inline-block'}),  
                html.Div([
                    dcc.Graph(id='indicator-graphic2',
                              config={'modeBarButtonsToRemove': ['sendDataToCloud', 'lasso2d', 'zoomIn2d', 'zoomOut2d', 'pan2d', 
                                                                 'zoom2d','resetScale2d'], 
                                    'displaylogo': False})
                    ], style={'width': '50%', 'display': 'inline-block'}),             
            ]),
    ])
@app.callback(

    dash.dependencies.Output('indicator-graphic1', 'figure'),
    [dash.dependencies.Input('outcome-id', 'value')])
def outcome_urban(outcome_id):
    dff = df[['year', 'wbhao_igen', 'centcity',outcome_id]]
    dff = dff[(dff.centcity == 1)]

    lines = {}
    data = []
    
    m_max = dff[outcome_id].max()
    m_min = dff[outcome_id].min()
    f = df[['year', 'wbhao_igen', 'centcity',outcome_id]]
    f = f[(f.centcity== 0)]
    f_max = f[outcome_id].max()
    f_min = f[outcome_id].min()
    if m_max>f_max:
        df_max = m_max
    elif m_max<f_max:
        df_max = f_max
    if m_min>f_min:
        df_min = f_min
    elif m_min<f_min:
        df_min = m_min
    if df_min<0.05:
        df_min = 0
        
    y_axis = {'title': '{0}'.format(outcome_id), 
              'hoverformat': ',.2f',
              'range': [df_min, df_max]}          
    legends={'orientation': 'h', 'xanchor': 'center', 'x': '0.5', 'y': '-0.22'}

    
    # Show three lines for each output
    generation = ['Hispanic All', 'White All','Hispanic 1st Generation', 'Hispanic 2nd Generation', 
                  'Hispanic 3rd Generation']
    for gen in generation:
        if '1st' in gen:
             lines = dict(
                 color = ("#6b6ecf"),
                 width = 2,
                 dash = 'dash')
        if '2nd' in gen:
             lines = dict(
                 color = ("#80b1d3"),
                 width = 2,
                 dash = 'dash')              
        if '3rd' in gen:
             lines = dict(
                 color = ("#fdb462"),
                 width = 2,
                 dash = 'dash')
        if 'White All' in gen:
              lines = dict(
                 color = ("#333333"),
                 width = 3)
        if 'Hispanic All' in gen:
               lines = dict(
                 color = ("#fb8072"),
                 width = 3)
        trace = go.Scatter(
            x = dff[(dff.wbhao_igen == gen)]['year'],
            y = dff[(dff.wbhao_igen == gen)][outcome_id],
            mode='lines',
            name = gen,
            line = lines,
            opacity = 0.8
            )      
        data.append(trace)

    return {
        'data' : data,
        'layout' : go.Layout(
            title='Urban',
            titlefont=dict(
                        family='Georgia'),
            xaxis={'title': 'Year'},
            yaxis=y_axis,
            legend = legends
        )
    }

@app.callback(

    dash.dependencies.Output('indicator-graphic2', 'figure'),
    [dash.dependencies.Input('outcome-id', 'value')])
def outcome_nonurban(outcome_id):
    dff = df[['year', 'wbhao_igen', 'centcity',outcome_id]]
    dff = dff[(dff.centcity == 0)]

    lines = {}
    data = []
    
    f_max = dff[outcome_id].max()
    f_min = dff[outcome_id].min()
    m = df[['year', 'wbhao_igen', 'centcity',outcome_id]]
    m = m[(m.centcity== 1)]
    m_max = m[outcome_id].max()
    m_min = m[outcome_id].min()
    if f_max>m_max:
        df_max = f_max
    elif f_max<m_max:
        df_max = m_max
    if f_min>m_min:
        df_min = m_min
    elif f_min<m_min:
        df_min = f_min
    if df_min<0.05:
        df_min = 0

    y_axis = {'title': '{0}'.format(outcome_id), 
              'hoverformat': ',.2f',
              'range': [df_min, df_max]}          
    legends={'orientation': 'h', 'xanchor': 'center', 'x': '0.5', 'y': '-0.22'}

    
    # Show three lines for each output
    generation = ['Hispanic All', 'White All','Hispanic 1st Generation', 'Hispanic 2nd Generation', 
                  'Hispanic 3rd Generation']
    for gen in generation:
        if '1st' in gen:
             lines = dict(
                 color = ("#6b6ecf"),
                 width = 2,
                 dash = 'dash')
        if '2nd' in gen:
             lines = dict(
                 color = ("#80b1d3"),
                 width = 2,
                 dash = 'dash')              
        if '3rd' in gen:
             lines = dict(
                 color = ("#fdb462"),
                 width = 2,
                 dash = 'dash')
        if 'White All' in gen:
              lines = dict(
                 color = ("#333333"),
                 width = 3)
        if 'Hispanic All' in gen:
               lines = dict(
                 color = ("#fb8072"),
                 width = 3)
        trace = go.Scatter(
            x = dff[(dff.wbhao_igen == gen)]['year'],
            y = dff[(dff.wbhao_igen == gen)][outcome_id],
            mode='lines',
            name = gen,
            line = lines,
            opacity = 0.8
            )      
        data.append(trace)

    return {
        'data' : data,
        'layout' : go.Layout(
            title = 'Non-Urban',
            titlefont=dict(
                        family='Georgia'),
            xaxis={'title': 'Year'},
            yaxis=y_axis,
            legend = legends
        )
    }
    
if __name__ == '__main__':
    app.run_server()

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Apr/2018 11:53:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 11:53:57] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 11:53:57] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 11:53:57] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 11:53:57] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 11:53:58] "GET /favicon.ico HTTP/1.1" 200 -