# Immigrant Project 

### Distribution of Immigrant Generation among Hispanics and Whites

At this point, what I have in mind is two graphs showing the trends in outcomes (like the one you prepared [here](https://caldercenter.org/data-visualizations/aggregated-number-graduates-education-nationally))

1.	Distribution of Immigrant Generation among Hispanics and Whites, 1994-2016: you can create this using main_national…looking at igen=”All” and using the variables gen1 gen2, and gen3. I think it would be useful to have 2 graphs side by side, one showing the distribution among Hispanics and the other showing the distribution among whites.
2.	Distribution of Immigrant Generation among Hispanics and Whites in Top Immigration States, 1994-2016: you can create this using main_topstates…looking at igen=”All” and using the variables gen1 gen2, and gen3. Two graphs, side-by-side, and with the option to choose the state.

  * LTHS: “% less than HS diploma”
  * College: “% with college degree”
  *	Hinsured: “% with health insurance”
  * rincp_all: “Average individual real income”
  *	employed: “% employed”
  *	married2: “% married”
  *	children: “% with children”
  * poverty; (% of families under the poverty line)
  * age; (Average age)
  * rinch_all; (median household income);

## Clean data

I want to make sure that the data is in a format that can be transformed into a dash app easily.

In [1]:
import pandas as pd
import os
import plotly.graph_objs as go
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State

In [2]:
os.chdir(r'H:\CALDER\CALDER Data Visualizations\Data\Immigrant Project')

In [3]:
nat = pd.read_csv('main_national.csv')

In [4]:
nat = nat.sort_values(by=['year', 'wbhao', 'igen'])
nat.head(9)

,year,wbhao,igen,lths,college,hinsured,employed,married2,children,gen1,gen2,gen3,rincp_all
3,1994,Hispanic,1st Generation,0.505530,0.098835,0.563049,0.678571,0.689724,0.725421,NaN,NaN,NaN,16157.772
5,1994,Hispanic,2nd Generation,0.271175,0.117982,0.756655,0.671149,0.581021,0.590973,NaN,NaN,NaN,24236.658
7,1994,Hispanic,3rd Generation,0.186292,0.096557,0.780923,0.782869,0.649603,0.658164,NaN,NaN,NaN,27468.213
9,1994,Hispanic,All,0.380639,0.102503,0.655657,0.700982,0.656673,0.680479,0.550558,0.218982,0.230460,19389.326
2,1994,White,1st Generation,0.117878,0.373306,0.819465,0.733179,0.760921,0.530015,NaN,NaN,NaN,30804.793
4,1994,White,2nd Generation,0.055666,0.354645,0.868807,0.807859,0.672146,0.485741,NaN,NaN,NaN,38959.621
6,1994,White,3rd Generation,0.080657,0.276775,0.863600,0.813620,0.700100,0.532252,NaN,NaN,NaN,35547.102
8,1994,White,All,0.080565,0.284902,0.862277,0.810314,0.700705,0.529443,0.036895,0.058630,0.904475,35547.102
11,1995,Hispanic,1st Generation,0.517231,0.088316,0.532448,0.682456,0.705492,0.728825,NaN,NaN,NaN,17410.000

In [5]:
# Rename Columns
pre = ['lths', 'college', 'hinsured', 'employed', 'married2', 'children', 'gen1', 'gen2', 'gen3','rincp_all']
post = ["% less than High School diploma", "% with College Degree", "% with Health Insurance", "% Employed", "% Married", 
        "% with Children", "Share of 1st Generation", "Share of 2nd Generation", "Share of 3rd Generation", 
        "Median Individual Real Income"]
for i in range(0, len(pre)):   
    nat.rename(columns={pre[i]: post[i]}, inplace=True)

nat.columns

Index(['year', 'wbhao', 'igen', '% less than High School diploma',
       '% with College Degree', '% with Health Insurance', '% Employed',
       '% Married', '% with Children', 'Share of 1st Generation',
       'Share of 2nd Generation', 'Share of 3rd Generation',
       'Median Individual Real Income'],
      dtype='object')

In [6]:
nat['wbhao_igen'] = nat['wbhao'] + ' ' + nat['igen']

### Drop Columns to match Umut's request in #1

In [7]:
nat = nat[nat.igen == 'All']

In [8]:
nat.columns

Index(['year', 'wbhao', 'igen', '% less than High School diploma',
       '% with College Degree', '% with Health Insurance', '% Employed',
       '% Married', '% with Children', 'Share of 1st Generation',
       'Share of 2nd Generation', 'Share of 3rd Generation',
       'Median Individual Real Income', 'wbhao_igen'],
      dtype='object')

In [9]:
nat = nat[['year', 'wbhao', 'igen', 'Share of 1st Generation','Share of 2nd Generation', 'Share of 3rd Generation',
           'wbhao_igen']]

In [10]:
nat['state'] = 'National'

## Append "Top_State" data set

You will be able to select the national data along with the state data using the "state" column.

### Import and Clean "top_state" data

In [11]:
state = pd.read_csv('main_topstates.csv')

In [12]:
state = state.sort_values(by=['year', 'state', 'wbhao'])
state.head(9)

,year,wbhao,state,igen,lths,college,hinsured,employed,married2,children,gen1,gen2,gen3,rincp_all
23,1994,Hispanic,California,1st Generation,0.578281,0.069639,0.559158,0.660304,0.708181,0.782131,NaN,NaN,NaN,16157.772
35,1994,Hispanic,California,2nd Generation,0.229561,0.090034,0.828209,0.766322,0.616886,0.555380,NaN,NaN,NaN,27726.738
47,1994,Hispanic,California,3rd Generation,0.091974,0.077231,0.848449,0.791233,0.636506,0.687663,NaN,NaN,NaN,33365.801
59,1994,Hispanic,California,All,0.423552,0.074302,0.660462,0.703786,0.679380,0.728175,0.639306,0.150298,0.210396,19389.326
22,1994,White,California,1st Generation,0.109510,0.413616,0.819607,0.717939,0.767810,0.579526,NaN,NaN,NaN,32477.123
34,1994,White,California,2nd Generation,0.058566,0.388762,0.862976,0.792943,0.634908,0.521915,NaN,NaN,NaN,41346.125
46,1994,White,California,3rd Generation,0.043372,0.321261,0.842302,0.803886,0.630651,0.491570,NaN,NaN,NaN,41740.375
58,1994,White,California,All,0.050509,0.335425,0.842201,0.795411,0.642978,0.501980,0.087061,0.090710,0.822229,41178.082
19,1994,Hispanic,Florida,1st Generation,0.298869,0.134267,0.574033,0.736406,0.655011,0.568187,NaN,NaN,NaN,19066.172

In [13]:
# Rename Columns
pre = ['lths', 'college', 'hinsured', 'employed', 'married2', 'children', 'gen1', 'gen2', 'gen3','rincp_all']
post = ["% less than High School diploma", "% with College Degree", "% with Health Insurance", "% Employed", "% Married", 
        "% with Children", "Share of 1st Generation", "Share of 2nd Generation", "Share of 3rd Generation", 
        "Median Individual Real Income"]
for i in range(0, len(pre)):   
    state.rename(columns={pre[i]: post[i]}, inplace=True)

state.columns

Index(['year', 'wbhao', 'state', 'igen', '% less than High School diploma',
       '% with College Degree', '% with Health Insurance', '% Employed',
       '% Married', '% with Children', 'Share of 1st Generation',
       'Share of 2nd Generation', 'Share of 3rd Generation',
       'Median Individual Real Income'],
      dtype='object')

In [14]:
state['wbhao_igen'] = state['wbhao'] + ' ' + state['igen']

In [15]:
state = state[state.igen == 'All']

In [16]:
state = state[['year', 'wbhao', 'igen', 'state', 'Share of 1st Generation','Share of 2nd Generation', 
               'Share of 3rd Generation', 'wbhao_igen']]

### Append

In [17]:
append = nat.append(state)

In [18]:
append = append.sort_values(by=['year', 'wbhao', 'igen'])

In [19]:
append.head(8)

,Share of 1st Generation,Share of 2nd Generation,Share of 3rd Generation,igen,state,wbhao,wbhao_igen,year
9,0.550558,0.218982,0.230460,All,National,Hispanic,Hispanic All,1994
59,0.639306,0.150298,0.210396,All,California,Hispanic,Hispanic All,1994
55,0.748032,0.196377,0.055591,All,Florida,Hispanic,Hispanic All,1994
53,0.668037,0.244457,0.087506,All,Illinois,Hispanic,Hispanic All,1994
51,0.595328,0.378894,0.025778,All,New Jersey,Hispanic,Hispanic All,1994
49,0.544786,0.400080,0.055134,All,New York,Hispanic,Hispanic All,1994
57,0.356711,0.202387,0.440901,All,Texas,Hispanic,Hispanic All,1994
8,0.036895,0.058630,0.904475,All,National,White,White All,1994

## Graph

Will try to create what Umut asked for in #1 above using the data structure above. If it proves too messy I'll restructure it long.

In [20]:
app = dash.Dash()

app.css.append_css({"external_url": "https://codepen.io/chriddyp/pen/bWLwgP.css"}) 

df = append

states = list(append['state'].unique())

# Organize where items will be on the page
app.layout = html.Div([
        html.H3(
            children='Distribution of Immigrant Generation among Hispanics and Whites, Nationally \
                        and in Top Immigration States',
            style={
                'textAlign': 'center', 'fontFamily' : 'Georgia'
            }
        ),
        html.Center([          
            html.Div([
                html.Div([html.P('Select State',id='state-title')],
                    style={'textAlign': 'center', 'fontFamily': 'Georgia'}),
                dcc.Dropdown(
                    id='state-id',
                    options=[{'label': i, 'value': i} for i in states],
                    value='California')
                ],style={'width': '50%','textAlign': 'center', 'fontFamily': 'Georgia', 'display': 'inline-block'}),        
            ]),
        html.Div([
            html.Div([
                dcc.Graph(id='indicator-graphic1',
                          config={'modeBarButtonsToRemove': ['sendDataToCloud', 'lasso2d', 'zoomIn2d', 'zoomOut2d', 'pan2d', 
                                                             'zoom2d','resetScale2d'], 
                                'displaylogo': False})
                ], style={'width': '50%', 'display': 'inline-block'}),  
            html.Div([
                dcc.Graph(id='indicator-graphic2',
                          config={'modeBarButtonsToRemove': ['sendDataToCloud', 'lasso2d', 'zoomIn2d', 'zoomOut2d', 'pan2d', 
                                                             'zoom2d','resetScale2d'], 
                                'displaylogo': False})
                ], style={'width': '50%', 'display': 'inline-block'}),             
        ]),
    ])
@app.callback(

    dash.dependencies.Output('indicator-graphic1', 'figure'),
    [dash.dependencies.Input('state-id', 'value')])
def outcome_hispanic(state_id):
    dff = df[['year', 'wbhao_igen', 'state','Share of 1st Generation','Share of 2nd Generation', 'Share of 3rd Generation']]
    dff = dff[(dff.state == state_id) & (dff.wbhao_igen == 'Hispanic All')]

    lines = {}
    data = []
    y_axis = {'title': '% in {0}'.format(state_id), 
              'hoverformat': ',.2f',
              'range' : [0,1]}          
    legends={'orientation': 'h', 'xanchor': 'center', 'x': '0.5', 'y': '-0.22'}

    
    outcomes = ['Share of 1st Generation','Share of 2nd Generation', 'Share of 3rd Generation']
    for gen in outcomes:
        if '1st' in gen:
             lines = dict(
                 color = ("#6b6ecf"),
                 width = 3)
        if '2nd' in gen:
             lines = dict(
                 color = ("#80b1d3"),
                 width = 3)
        if '3rd' in gen:
             lines = dict(
                 color = ("#fdb462"),
                 width = 3)
        trace = go.Scatter(
            x = dff['year'],
            y = dff[gen],
            mode='lines',
            name = gen,
            line = lines,
            opacity = 0.8
            )
        
        data.append(trace)


    return {
        'data' : data,
        'layout' : go.Layout(
            title='Hispanic',
            titlefont=dict(
                        family='Georgia'),
            xaxis={'title': 'Year'},
            yaxis=y_axis,
            legend = legends
        )
    }

@app.callback(

    dash.dependencies.Output('indicator-graphic2', 'figure'),
    [dash.dependencies.Input('state-id', 'value')])
def outcome_white(state_id):
    dff = df[['year', 'wbhao_igen', 'state','Share of 1st Generation','Share of 2nd Generation', 'Share of 3rd Generation']]
    dff = dff[(dff.state == state_id) & (dff.wbhao_igen == 'White All')]

    lines = {}
    data = []
    y_axis = {'title': '% in {0}'.format(state_id), 
              'hoverformat': ',.2f',
              'range' : [0,1]}          
    legends={'orientation': 'h', 'xanchor': 'center', 'x': '0.5', 'y': '-0.22'}

    
    outcomes = ['Share of 1st Generation','Share of 2nd Generation', 'Share of 3rd Generation']
    for gen in outcomes:
        if '1st' in gen:
             lines = dict(
                 color = ("#6b6ecf"),
                 width = 3)
        if '2nd' in gen:
             lines = dict(
                 color = ("#80b1d3"),
                 width = 3)
        if '3rd' in gen:
             lines = dict(
                 color = ("#fdb462"),
                 width = 3)
        trace = go.Scatter(
            x = dff['year'],
            y = dff[gen],
            mode='lines',
            name = gen,
            line = lines,
            opacity = 0.8
            )
        
        data.append(trace)


    return {
        'data' : data,
        'layout' : go.Layout(
            title = 'White',
            titlefont=dict(
                        family='Georgia'),
            xaxis={'title': 'Year'},
            yaxis=y_axis,
            legend = legends
        )
    }
    
if __name__ == '__main__':
    app.run_server()

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Apr/2018 09:32:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:04] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:04] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:04] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:04] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:04] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:17] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:17] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:20] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:20] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:24] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:24] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:29] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:32] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:32] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:37] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:37] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:51] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:51] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:54] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:32:54] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:33:03] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:33:03] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:33:15] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [06/Apr/2018 09:33:15] "POST /_dash-update-component HTTP/1.1" 200 -